# Generated by Django 5.1.5 on 2025-02-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=40)),
            ],
        ),
    ]
